export const presets = [
    {
        name: 'Note',
        values: [
            'A',
            'A#/Bb',
            'B',
            'C',
            'C#/Db',
            'D',
            'D#/Eb',
            'E',
            'F',
            'F#/Gb',
            'G',
            'G#/Ab',
        ],
    },
    {
        name: 'Chord',
        values: ['Ⅰ', 'Ⅱ', 'Ⅲ', 'Ⅳ', 'Ⅴ', 'Ⅵ', 'Ⅶ'],
    },
    {
        name: 'Time Signature',
        values: [
            '3/4',
            '4/4',
            '5/4',
            '6/4',
            '7/4',
            '6/8',
            '7/8',
            '9/8',
            '10/8',
            '11/8',
            '12/8',
            '13/8',
            '14/8',
            '15/8',
            '16/8',
        ],
    },
    {
        name: 'Scales',
        values: [
            '15 equal temperament',
            '16 equal temperament',
            '17 equal temperament',
            '19 equal temperament',
            '21 equal temperament',
            'Acoustic scale',
            'Lydian dominant scale',
            'Aeolian mode',
            'natural minor scale',
            'Algerian scale',
            'Alpha scale',
            'Altered scale',
            'Super Locrian scale',
            'Augmented scale',
            'Bebop dominant scale',
            'Beta scale',
            'Blues scale',
            'Bohlen–Pierce scale',
            'Chromatic scale',
            'Delta scale',
            'Dorian mode',
            'Double harmonic scale',
            'Enigmatic scale',
            'Euler–Fokker genus',
            'Flamenco mode',
            'Gamma scale',
            '"Gypsy" scale',
            'Half diminished scale',
            'Harmonic major scale',
            'Harmonic minor scale',
            'Harmonic Scale',
            'Hexany',
            'Hirajoshi scale',
            'Hungarian "Gypsy" scale',
            'Hungarian minor scale',
            'Hungarian major scale',
            'In scale',
            'Insen scale',
            'Ionian mode',
            'major scale',
            'Istrian scale',
            'Iwato scale',
            'Locrian mode',
            'Lydian augmented scale',
            'Lydian diminished scale',
            'Lydian mode',
            'bebop scale',
            'Major Locrian scale',
            'pentatonic scale',
            'Melodic minor scale',
            'Melodic minor scale',
            'Minor pentatonic scale',
            'Mixolydian mode',
            'Adonai malakh mode',
            'Neapolitan major scale',
            'Neapolitan minor scale',
            'Non-Pythagorean scale',
            'Octatonic scale',
            'Pelog',
            'Persian scale',
            'Phrygian dominant scale',
            'Phrygian mode',
            'Prometheus scale',
            'Quarter tone scale',
            'Scale of harmonics',
            'Slendro',
            'Tritone scale',
            'tritone scale',
            'Ukrainian Dorian scale',
            'scale of harmonics',
            'Whole tone scale',
            'Yo scale',
        ],
    },
    {
        name: 'Plugin',
        values: [
            'Nexus',
            'uJam guit',
            'uJam drums',
            'uJam bass',
            'Omnisphere',
            'Sakura',
            'Flex',
        ],
    },
];
